"""Thermodynamic constants, largely taken from Wallace and Hobbs Ch 3."""

AVOGRADROS_NUMBER = 6.022E23
UNIVERSAL_GAS_CONSTANT = 8.3145  # J K-1 mol-1 


MOLECULAR_WEIGHT_FOR_DRY_AIR = 28.97 # g
MOLECULAR_WEIGHT_FOR_WATER = 18.016 # g
SPECIFIC_GAS_CONSTANT_FOR_DRY_AIR = (UNIVERSAL_GAS_CONSTANT /
                                     MOLECULAR_WEIGHT_FOR_DRY_AIR)
SPECIFIC_GAS_CONSTANT_FOR_WATER_VAPOUR = (UNIVERSAL_GAS_CONSTANT /
                                          MOLECULAR_WEIGHT_FOR_WATER)

GRAVITATIONAL_ACCELERATION = 9.81 # m s-2
