import os

from jazz import cmip5


def test_path():
    """Test the path generated by cmip5.path exists."""
    path = cmip5.path('HadGEM2-ES', 'historical', 'mon', 'atmos', 'Amon', 
                      'r1i1p1', 'ts')
    assert os.path.exists('/'.join(path.split('/')[0:-1]))


def test_common_dict():
    """Test that cmip5.common_dict removes keys correctly."""
    dictionary1 = {'key1':1, 'key2':2}
    dictionary2 = {'key1':1, 'key2':3}
    common = cmip5.common_dict([dictionary1, dictionary2])
    assert 'key2' not in common.keys()
